insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Tobye', 'Atlay', 'Software Engineer IV', '2023/12/08', 64028.09, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Wallie', 'Ledes', 'Administrative Officer', '2024/05/17', 30509.28, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Dorie', 'Olliffe', 'Recruiting Manager', '2024/01/29', 69969.28, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Stuart', 'Shutte', 'Design Engineer', '2024/05/30', 47928.3, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Brendin', 'Joris', 'Legal Assistant', '2024/06/01', 31069.28, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Livvyy', 'Lanchbury', 'Human Resources Manager', '2023/12/24', 43821.22, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Dan', 'Craw', 'Environmental Specialist', '2023/12/24', 69438.9, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Catherina', 'Matushenko', 'Director of Sales', '2024/01/07', 37758.2, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Perry', 'Haimes', 'Research Nurse', '2024/04/14', 38670.39, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Olvan', 'Halms', 'Media Manager IV', '2024/05/24', 42286.09, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Deloris', 'Perrigo', 'Financial Analyst', '2023/12/06', 79711.57, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Allie', 'Boon', 'Research Nurse', '2024/07/10', 69724.51, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Morgun', 'Berick', 'Executive Secretary', '2024/06/23', 30522.2, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Maren', 'Leversuch', 'Account Representative IV', '2024/02/05', 53910.22, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Giuseppe', 'McEttigen', 'Cost Accountant', '2024/04/19', 45215.09, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Berenice', 'Nusche', 'Payment Adjustment Coordinator', '2024/09/28', 46756.37, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Ozzy', 'Evanson', 'Graphic Designer', '2023/12/04', 71728.44, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Germana', 'Blowes', 'Safety Technician III', '2024/05/22', 36454.53, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Brook', 'Huelin', 'Senior Developer', '2024/03/13', 50396.98, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Ali', 'Rendell', 'Help Desk Technician', '2024/03/12', 33945.66, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Brodie', 'Andras', 'Electrical Engineer', '2024/10/22', 29395.37, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Theo', 'Clynmans', 'Software Engineer IV', '2024/01/10', 31450.71, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Jorey', 'Erskin', 'Computer Systems Analyst II', '2024/06/15', 52738.51, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Amble', 'Marcam', 'Computer Systems Analyst IV', '2024/02/19', 71694.91, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Cody', 'Marxsen', 'Analog Circuit Design manager', '2024/11/03', 55872.5, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Neille', 'Shireff', 'Structural Analysis Engineer', '2024/10/15', 26567.59, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Griff', 'Adne', 'Account Representative I', '2024/10/13', 44531.83, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Bren', 'Landeg', 'Internal Auditor', '2023/12/04', 30782.75, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Carolin', 'Mendenhall', 'Nurse', '2024/08/10', 49123.82, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Portia', 'Skyrm', 'Chemical Engineer', '2024/08/18', 63200.62, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Halley', 'Schistl', 'Developer I', '2024/08/08', 37602.34, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Wylie', 'Jewise', 'Chemical Engineer', '2024/02/07', 47593.83, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Berta', 'Peirone', 'Pharmacist', '2024/04/03', 30397.63, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Rayner', 'Shrigley', 'Payment Adjustment Coordinator', '2023/12/28', 74307.69, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Isa', 'Evemy', 'Electrical Engineer', '2024/08/26', 37534.33, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Akim', 'Doody', 'Marketing Assistant', '2024/11/06', 62274.73, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Lenka', 'Tague', 'Speech Pathologist', '2023/12/05', 73002.3, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Danyelle', 'Grafom', 'Developer II', '2024/09/08', 43930.35, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Kristien', 'Adam', 'Librarian', '2024/01/05', 48990.91, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Aprilette', 'Yeabsley', 'Chemical Engineer', '2024/08/16', 48945.38, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Conn', 'Kevern', 'Account Representative I', '2024/11/04', 56875.81, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Mar', 'Sarle', 'Account Coordinator', '2023/11/29', 79188.22, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Lissie', 'Pratt', 'Speech Pathologist', '2023/11/19', 55592.31, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Rowney', 'Ettery', 'Recruiter', '2024/04/21', 70603.09, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Eberhard', 'Lyons', 'Engineer I', '2024/05/06', 60658.7, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Ingelbert', 'Chezelle', 'Structural Engineer', '2024/10/09', 47760.83, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Ania', 'Godspeede', 'VP Sales', '2024/03/06', 27766.2, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Marta', 'Balentyne', 'Senior Sales Associate', '2024/05/16', 55971.54, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Hilario', 'Bortolazzi', 'Senior Quality Engineer', '2024/08/24', 48815.55, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Electra', 'Guerrazzi', 'VP Product Management', '2024/01/31', 59659.06, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Cobbie', 'Scottrell', 'Marketing Assistant', '2024/10/21', 59441.09, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Zebulen', 'Winstone', 'Human Resources Manager', '2024/09/20', 26800.12, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Nilson', 'Leguay', 'Paralegal', '2024/07/21', 78380.52, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Afton', 'Tugwell', 'Structural Engineer', '2024/04/15', 64408.18, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Fallon', 'Diggin', 'Registered Nurse', '2024/01/27', 64806.91, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Bernhard', 'Doherty', 'Assistant Professor', '2024/09/30', 47884.14, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Hoyt', 'Sinkin', 'Senior Financial Analyst', '2024/03/21', 62517.09, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Alan', 'MacIlory', 'Software Test Engineer I', '2024/09/23', 73813.6, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Ertha', 'Bestman', 'Environmental Tech', '2024/10/18', 33192.67, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Aimil', 'Vickerman', 'Biostatistician III', '2024/03/09', 68547.8, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Malchy', 'Agnew', 'Quality Control Specialist', '2024/04/25', 38381.76, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Charin', 'Seakin', 'Budget/Accounting Analyst I', '2024/01/16', 31380.78, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Philly', 'Irvin', 'Quality Engineer', '2024/11/15', 53704.39, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Hulda', 'Schollar', 'Nurse Practicioner', '2024/01/26', 77722.51, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Sutton', 'Gentreau', 'Accounting Assistant I', '2024/04/02', 46690.05, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Mathilde', 'Marjoram', 'Media Manager II', '2024/01/21', 79686.62, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Jehu', 'Belmont', 'Tax Accountant', '2024/06/21', 46946.29, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Teodoor', 'Naulty', 'Developer II', '2024/05/02', 31122.51, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Evaleen', 'Hannabus', 'Statistician IV', '2024/02/12', 72607.23, 1);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Thane', 'MacDirmid', 'Geological Engineer', '2024/04/19', 68127.41, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Lana', 'Di Napoli', 'Junior Executive', '2024/02/04', 57929.49, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Chelsea', 'Jenkison', 'Director of Sales', '2024/01/26', 35752.51, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Stanislaus', 'Antrack', 'Financial Analyst', '2023/11/26', 70910.9, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Lyn', 'Lightowlers', 'Accounting Assistant II', '2024/03/28', 38159.07, 3);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Karlan', 'Tabary', 'Account Executive', '2024/07/18', 77568.67, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Mirelle', 'Peakman', 'Electrical Engineer', '2024/01/21', 67571.26, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Joby', 'Sporner', 'Clinical Specialist', '2023/12/06', 51867.43, 5);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Iver', 'Beeze', 'Senior Cost Accountant', '2024/10/27', 27746.63, 4);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Darrin', 'Feitosa', 'Senior Developer', '2024/03/15', 69876.17, 2);
insert into employee (first_name, last_name, position, hire_date, salary, branch_id) values ('Harriett', 'Ikringill', 'Junior Executive', '2024/06/18', 71846.23, 5);
