// Season2001-2002
let
  Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/IvanRamosDataTech/Premier-League/master/rawdata/Season2001-2002.csv"), [Delimiter = ",", Columns = 48, QuoteStyle = QuoteStyle.None]),
  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Div", type text}, {"Date", type text}, {"HomeTeam", type text}, {"AwayTeam", type text}, {"FTHG", Int64.Type}, {"FTAG", Int64.Type}, {"FTR", type text}, {"HTHG", Int64.Type}, {"HTAG", Int64.Type}, {"HTR", type text}, {"Attendance", Int64.Type}, {"Referee", type text}, {"HS", Int64.Type}, {"AS", Int64.Type}, {"HST", Int64.Type}, {"AST", Int64.Type}, {"HHW", Int64.Type}, {"AHW", Int64.Type}, {"HC", Int64.Type}, {"AC", Int64.Type}, {"HF", Int64.Type}, {"AF", Int64.Type}, {"HO", Int64.Type}, {"AO", Int64.Type}, {"HY", Int64.Type}, {"AY", Int64.Type}, {"HR", Int64.Type}, {"AR", Int64.Type}, {"HBP", Int64.Type}, {"ABP", Int64.Type}, {"GBH", type number}, {"GBD", type number}, {"GBA", type number}, {"IWH", type number}, {"IWD", type number}, {"IWA", type number}, {"LBH", type number}, {"LBD", type number}, {"LBA", type number}, {"SBH", type number}, {"SBD", type number}, {"SBA", type number}, {"SYH", type number}, {"SYD", type number}, {"SYA", type number}, {"WHH", type number}, {"WHD", type number}, {"WHA", type number}}),
#"Removed columns" = Table.RemoveColumns(#"Changed column type", {"Div"}),
#"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"FTHG", "FullTimeHomeTeamGoals"}, {"FTAG", "FullTimeAwayTeamGoals"}, {"FTR", "FullTimeResult"}, {"HTHG", "HalfTimeHomeTeamGoals"}, {"HTAG", "HalfTimeAwayTeamGoals"}, {"HTR", "HalfTimeResult"}, {"HS", "HomeTeamShots"}, {"AS", "AwayTeamShots"}, {"HST", "HomeTeamShotsOnTarget"}, {"AST", "AwayTeamShotsOnTarget"}, {"HF", "HomeTeamFouls"}, {"AF", "AwayTeamFouls"}, {"HC", "HomeTeamCorners"}, {"AC", "AwayTeamCorners"}, {"HY", "HomeTeamYellowCards"}, {"AY", "AwayTeamYellowCards"}, {"HR", "HomeTeamRedCards"}, {"AR", "AwayTeamReadCards"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns", {"Attendance", "HHW", "AHW", "HBP", "ABP", "GBH", "GBD", "GBA", "IWH", "IWD", "IWA", "LBH", "LBD", "LBA", "SBH", "SBD", "SBA", "SYH", "SYD", "SYA", "WHH", "WHD", "WHA"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Removed columns 1", {{"HO", "HomeOffsides"}, {"AO", "AwayOffsides"}}),
  #"Reordered columns" = Table.ReorderColumns(#"Renamed columns 1", {"Date", "HomeTeam", "AwayTeam", "FullTimeHomeTeamGoals", "FullTimeAwayTeamGoals", "FullTimeResult", "HalfTimeHomeTeamGoals", "HalfTimeAwayTeamGoals", "HalfTimeResult", "Referee", "HomeTeamShots", "AwayTeamShots", "HomeTeamShotsOnTarget", "AwayTeamShotsOnTarget", "HomeTeamCorners", "AwayTeamCorners", "HomeTeamFouls", "AwayTeamFouls", "HomeTeamYellowCards", "AwayTeamYellowCards", "HomeTeamRedCards", "AwayTeamReadCards", "HomeOffsides", "AwayOffsides"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Reordered columns", "Season", each "2001-2002"), {{"Season", type text}}),
  #"Reordered columns 1" = Table.ReorderColumns(#"Added custom", {"Season", "Date", "HomeTeam", "AwayTeam", "FullTimeHomeTeamGoals", "FullTimeAwayTeamGoals", "FullTimeResult", "HalfTimeHomeTeamGoals", "HalfTimeAwayTeamGoals", "HalfTimeResult", "Referee", "HomeTeamShots", "AwayTeamShots", "HomeTeamShotsOnTarget", "AwayTeamShotsOnTarget", "HomeTeamCorners", "AwayTeamCorners", "HomeTeamFouls", "AwayTeamFouls", "HomeTeamYellowCards", "AwayTeamYellowCards", "HomeTeamRedCards", "AwayTeamReadCards", "HomeOffsides", "AwayOffsides"}),
  #"Removed columns 2" = Table.RemoveColumns(#"Reordered columns 1", {"HomeOffsides", "AwayOffsides"}),
  #"Changed type to date" = Table.TransformColumnTypes(#"Removed columns 2", {{"Date", type date}}, "es-MX")
in
  #"Changed type to date"