// Season2019-2020
let
  Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/IvanRamosDataTech/Premier-League/master/rawdata/Season2019-2020.csv"), [Delimiter = ",", Columns = 106, QuoteStyle = QuoteStyle.None]),
  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Div", type text}, {"Date", type text}, {"Time", type time}, {"HomeTeam", type text}, {"AwayTeam", type text}, {"FTHG", Int64.Type}, {"FTAG", Int64.Type}, {"FTR", type text}, {"HTHG", Int64.Type}, {"HTAG", Int64.Type}, {"HTR", type text}, {"Referee", type text}, {"HS", Int64.Type}, {"AS", Int64.Type}, {"HST", Int64.Type}, {"AST", Int64.Type}, {"HF", Int64.Type}, {"AF", Int64.Type}, {"HC", Int64.Type}, {"AC", Int64.Type}, {"HY", Int64.Type}, {"AY", Int64.Type}, {"HR", Int64.Type}, {"AR", Int64.Type}, {"B365H", type number}, {"B365D", type number}, {"B365A", type number}, {"BWH", type number}, {"BWD", type number}, {"BWA", type number}, {"IWH", type number}, {"IWD", type number}, {"IWA", type number}, {"PSH", type number}, {"PSD", type number}, {"PSA", type number}, {"WHH", type number}, {"WHD", type number}, {"WHA", type number}, {"VCH", type number}, {"VCD", type number}, {"VCA", type number}, {"MaxH", type number}, {"MaxD", type number}, {"MaxA", type number}, {"AvgH", type number}, {"AvgD", type number}, {"AvgA", type number}, {"B365>2.5", type number}, {"B365<2.5", type number}, {"P>2.5", type number}, {"P<2.5", type number}, {"Max>2.5", type number}, {"Max<2.5", type number}, {"Avg>2.5", type number}, {"Avg<2.5", type number}, {"AHh", type number}, {"B365AHH", type number}, {"B365AHA", type number}, {"PAHH", type number}, {"PAHA", type number}, {"MaxAHH", type number}, {"MaxAHA", type number}, {"AvgAHH", type number}, {"AvgAHA", type number}, {"B365CH", type number}, {"B365CD", type number}, {"B365CA", type number}, {"BWCH", type number}, {"BWCD", type number}, {"BWCA", type number}, {"IWCH", type number}, {"IWCD", type number}, {"IWCA", type number}, {"PSCH", type number}, {"PSCD", type number}, {"PSCA", type number}, {"WHCH", type number}, {"WHCD", type number}, {"WHCA", type number}, {"VCCH", type number}, {"VCCD", type number}, {"VCCA", type number}, {"MaxCH", type number}, {"MaxCD", type number}, {"MaxCA", type number}, {"AvgCH", type number}, {"AvgCD", type number}, {"AvgCA", type number}, {"B365C>2.5", type number}, {"B365C<2.5", type number}, {"PC>2.5", type number}, {"PC<2.5", type number}, {"MaxC>2.5", type number}, {"MaxC<2.5", type number}, {"AvgC>2.5", type number}, {"AvgC<2.5", type number}, {"AHCh", type number}, {"B365CAHH", type number}, {"B365CAHA", type number}, {"PCAHH", type number}, {"PCAHA", type number}, {"MaxCAHH", type number}, {"MaxCAHA", type number}, {"AvgCAHH", type number}, {"AvgCAHA", type number}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"Div"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"FTHG", "FullTimeHomeTeamGoals"}, {"FTAG", "FullTimeAwayTeamGoals"}, {"FTR", "FullTimeResult"}, {"HTHG", "HalfTimeHomeTeamGoals"}, {"HTAG", "HalfTimeAwayTeamGoals"}, {"HTR", "HalfTimeResult"}, {"HS", "HomeTeamShots"}, {"AS", "AwayTeamShots"}, {"HST", "HomeTeamShotsOnTarget"}, {"AST", "AwayTeamShotsOnTarget"}, {"HF", "HomeTeamFouls"}, {"AF", "AwayTeamFouls"}, {"HC", "HomeTeamCorners"}, {"AC", "AwayTeamCorners"}, {"HY", "HomeTeamYellowCards"}, {"AY", "AwayTeamYellowCards"}, {"HR", "HomeTeamRedCards"}, {"AR", "AwayTeamReadCards"}, {"B365H", "B365HomeTeam"}, {"B365D", "B365Draw"}, {"B365A", "B365AwayTeam"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns", {"BWH", "BWD", "BWA", "IWH", "IWD", "IWA", "PSH", "PSD", "PSA", "WHH", "WHD", "WHA", "VCH", "VCD", "VCA"}),
  #"Renamed columns 1" = Table.RenameColumns(#"Removed columns 1", {{"MaxH", "MarketMaxHomeTeam"}, {"MaxD", "MarketMaxDraw"}, {"MaxA", "MarketMaxAwayTeam"}, {"AvgH", "MarketAvgHomeTeam"}, {"AvgD", "MarketAvgDraw"}, {"AvgA", "MarketAvgAwayTeam"}, {"B365>2.5", "B365Over2.5Goals"}, {"B365<2.5", "B365Under2.5Goals"}}),
  #"Removed columns 2" = Table.RemoveColumns(#"Renamed columns 1", {"P>2.5", "P<2.5"}),
  #"Renamed columns 2" = Table.RenameColumns(#"Removed columns 2", {{"Max>2.5", "MarketMaxOver2.5Goals"}, {"Max<2.5", "MarketMaxUnder2.5Goals"}, {"Avg>2.5", "MarketAvgOver2.5Goals"}, {"Avg<2.5", "MarketAvgUnder2.5Goals"}}),
  #"Removed columns 3" = Table.RemoveColumns(#"Renamed columns 2", {"AHh", "B365AHH", "B365AHA", "PAHH", "PAHA", "MaxAHH", "MaxAHA", "AvgAHH", "AvgAHA", "B365CH", "B365CD", "B365CA", "BWCH", "BWCD", "BWCA", "IWCH", "IWCD", "IWCA", "PSCH", "PSCD", "PSCA", "WHCH", "WHCD", "WHCA", "VCCH", "VCCD", "VCCA", "MaxCH", "MaxCD", "MaxCA", "AvgCH", "AvgCD", "AvgCA", "B365C>2.5", "B365C<2.5", "PC>2.5", "PC<2.5", "MaxC>2.5", "MaxC<2.5", "AvgC>2.5", "AvgC<2.5", "AHCh", "B365CAHH", "B365CAHA", "PCAHH", "PCAHA", "MaxCAHH", "MaxCAHA", "AvgCAHH", "AvgCAHA"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns 3", "Season", each "2019-2020"), {{"Season", type text}}),
  #"Reordered columns" = Table.ReorderColumns(#"Added custom", {"Season", "Date", "Time", "HomeTeam", "AwayTeam", "FullTimeHomeTeamGoals", "FullTimeAwayTeamGoals", "FullTimeResult", "HalfTimeHomeTeamGoals", "HalfTimeAwayTeamGoals", "HalfTimeResult", "Referee", "HomeTeamShots", "AwayTeamShots", "HomeTeamShotsOnTarget", "AwayTeamShotsOnTarget", "HomeTeamFouls", "AwayTeamFouls", "HomeTeamCorners", "AwayTeamCorners", "HomeTeamYellowCards", "AwayTeamYellowCards", "HomeTeamRedCards", "AwayTeamReadCards", "B365HomeTeam", "B365Draw", "B365AwayTeam", "MarketMaxHomeTeam", "MarketMaxDraw", "MarketMaxAwayTeam", "MarketAvgHomeTeam", "MarketAvgDraw", "MarketAvgAwayTeam", "B365Over2.5Goals", "B365Under2.5Goals", "MarketMaxOver2.5Goals", "MarketMaxUnder2.5Goals", "MarketAvgOver2.5Goals", "MarketAvgUnder2.5Goals"}),
  #"Changed type to date" = Table.TransformColumnTypes(#"Reordered columns", {{"Date", type date}}, "es-MX")
in
  #"Changed type to date"