// Season2003-2004
let
  Source = Csv.Document(Web.Contents("https://raw.githubusercontent.com/IvanRamosDataTech/Premier-League/master/rawdata/Season2003-2004.csv"), [Delimiter = ",", Columns = 57, QuoteStyle = QuoteStyle.None]),
  #"Promoted headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
  #"Changed column type" = Table.TransformColumnTypes(#"Promoted headers", {{"Div", type text}, {"Date", type text}, {"HomeTeam", type text}, {"AwayTeam", type text}, {"FTHG", Int64.Type}, {"FTAG", Int64.Type}, {"FTR", type text}, {"HTHG", Int64.Type}, {"HTAG", Int64.Type}, {"HTR", type text}, {"Referee", type text}, {"HS", Int64.Type}, {"AS", Int64.Type}, {"HST", Int64.Type}, {"AST", Int64.Type}, {"HF", Int64.Type}, {"AF", Int64.Type}, {"HC", Int64.Type}, {"AC", Int64.Type}, {"HY", Int64.Type}, {"AY", Int64.Type}, {"HR", Int64.Type}, {"AR", Int64.Type}, {"B365H", type number}, {"B365D", type number}, {"B365A", type number}, {"GBH", type number}, {"GBD", type number}, {"GBA", type number}, {"IWH", type number}, {"IWD", type number}, {"IWA", type number}, {"LBH", type number}, {"LBD", type number}, {"LBA", type number}, {"SOH", type number}, {"SOD", type number}, {"SOA", type number}, {"SBH", type number}, {"SBD", type number}, {"SBA", type number}, {"WHH", type number}, {"WHD", type number}, {"WHA", type number}, {"GB>2.5", type number}, {"GB<2.5", type number}, {"B365>2.5", type number}, {"B365<2.5", type number}, {"GBAHH", type number}, {"GBAHA", type number}, {"GBAH", type number}, {"LBAHH", type number}, {"LBAHA", type number}, {"LBAH", type number}, {"B365AHH", type number}, {"B365AHA", type number}, {"B365AH", type number}}),
  #"Removed columns" = Table.RemoveColumns(#"Changed column type", {"Div"}),
  #"Renamed columns" = Table.RenameColumns(#"Removed columns", {{"FTHG", "FullTimeHomeTeamGoals"}, {"FTAG", "FullTimeAwayTeamGoals"}, {"FTR", "FullTimeResult"}, {"HTHG", "HalfTimeHomeTeamGoals"}, {"HTAG", "HalfTimeAwayTeamGoals"}, {"HTR", "HalfTimeResult"}, {"HS", "HomeTeamShots"}, {"AS", "AwayTeamShots"}, {"HST", "HomeTeamShotsOnTarget"}, {"AST", "AwayTeamShotsOnTarget"}, {"HF", "HomeTeamFouls"}, {"AF", "AwayTeamFouls"}, {"HC", "HomeTeamCorners"}, {"AC", "AwayTeamCorners"}, {"HY", "HomeTeamYellowCards"}, {"AY", "AwayTeamYellowCards"}, {"HR", "HomeTeamRedCards"}, {"AR", "AwayTeamReadCards"}, {"B365H", "B365HomeTeam"}, {"B365D", "B365Draw"}, {"B365A", "B365AwayTeam"}, {"B365>2.5", "B365Over2.5Goals"}, {"B365<2.5", "B365Under2.5Goals"}}),
  #"Removed columns 1" = Table.RemoveColumns(#"Renamed columns", {"IWH", "IWD", "IWA", "WHH", "WHD", "WHA"}),
  #"Added custom" = Table.TransformColumnTypes(Table.AddColumn(#"Removed columns 1", "Season", each "2003-2004"), {{"Season", type text}}),
  #"Reordered columns" = Table.ReorderColumns(#"Added custom", {"Season", "Date", "HomeTeam", "AwayTeam", "FullTimeHomeTeamGoals", "FullTimeAwayTeamGoals", "FullTimeResult", "HalfTimeHomeTeamGoals", "HalfTimeAwayTeamGoals", "HalfTimeResult", "Referee", "HomeTeamShots", "AwayTeamShots", "HomeTeamShotsOnTarget", "AwayTeamShotsOnTarget", "HomeTeamFouls", "AwayTeamFouls", "HomeTeamCorners", "AwayTeamCorners", "HomeTeamYellowCards", "AwayTeamYellowCards", "HomeTeamRedCards", "AwayTeamReadCards", "B365HomeTeam", "B365Draw", "B365AwayTeam"}),
  #"Removed columns 2" = Table.RemoveColumns(#"Reordered columns", {"LBH", "LBD", "LBA", "GBH", "GBD", "GBA", "SBH", "SBD", "SBA", "GB>2.5", "GB<2.5", "GBAHH", "GBAHA", "GBAH", "LBAHH", "LBAHA", "LBAH", "B365AHH", "B365AHA", "B365AH", "SOD", "SOA", "SOH"}),
  #"Reordered columns 1" = Table.ReorderColumns(#"Removed columns 2", {"Season", "Date", "HomeTeam", "AwayTeam", "FullTimeHomeTeamGoals", "FullTimeAwayTeamGoals", "FullTimeResult", "HalfTimeHomeTeamGoals", "HalfTimeAwayTeamGoals", "HalfTimeResult", "Referee", "HomeTeamShots", "AwayTeamShots", "HomeTeamShotsOnTarget", "AwayTeamShotsOnTarget", "HomeTeamFouls", "AwayTeamFouls", "HomeTeamCorners", "AwayTeamCorners", "HomeTeamYellowCards", "AwayTeamYellowCards", "HomeTeamRedCards", "AwayTeamReadCards", "B365HomeTeam", "B365Draw", "B365AwayTeam", "B365Over2.5Goals", "B365Under2.5Goals"}),
  #"Changed type to date" = Table.TransformColumnTypes(#"Reordered columns 1", {{"Date", type date}}, "es-MX")
in
  #"Changed type to date"